export const FETCH_COCKTAIL = "FETCH_COCKTAIL";
export const SET_COCKTAIL = "SET_COCKTAIL";

export const FETCH_COCKTAILS = "FETCH_COCKTAILS";
export const SET_COCKTAILS = "SET_COCKTAILS";

export const FETCH_RANDOM_DRINK = "FETCH_RANDOM_DRINK";
export const SET_RANDOM_DRINK = "SET_RANDOM_DRINK";
